# This config file is created by 'aws-prereqs' terraform scripts.
# Please reference this file in future terraform deployments.
aws_region: us-east-2
project_shortname: RedshiftTest01
project_tags:
  admin_contact: admin.email@noreply.com
